apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: iscc-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/eshghi26/iscckustomize.git
        revision: HEAD
        directories:
          - path: apps/*/*
  goTemplate: true
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 2}}-app'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}-{{index .path.segments 2}}'
      sources:
        - repoURL: https://github.com/eshghi26/iscckustomize.git
          targetRevision: HEAD
          path: charts/{{index .path.segments 1}}
          helm:
            valueFiles:
              - $values/apps/{{index .path.segments 1}}/{{index .path.segments 2}}/values.yaml
        - repoURL: https://github.com/eshghi26/iscckustomize.git
          targetRevision: HEAD
          ref: values
          path: apps/{{index .path.segments 1}}/{{index .path.segments 2}}
