apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-development
  namespace: argocd
spec:
  destination:
    namespace: nextcloud-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/eshghi26/iscckustomize.git
    targetRevision: main
    path: apps/nextcloud/overlays/development
    plugin:
      name: kustomize