apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: mariadb-galera
    repo: https://charts.bitnami.com/bitnami
    version: 7.0.0  # Use the latest version
    releaseName: mariadb
    namespace: isccdb-dev