apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: isccdb-dev

helmCharts:
  - name: mariadb
    repo: file://../../../charts/mariadb
    releaseName: mariadb
    version: 1.0.0
    namespace: isccdb-dev
    valuesFile: values.yaml